name: flutter_ffmpeg_fijkplayer
description: Flutter plugin to run FFmpeg on mobile platforms. Supports iOS and Android.
version: 0.0.1
homepage: https://github.com/martytsaitw/flutter-ffmpeg-fijkplayer

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.10.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  fijkplayer: ^0.8.7

dev_dependencies:
  path_provider: ^1.6.16
  path: ^1.7.0

flutter:
  plugin:
    platforms:
      android:
        package: com.arthenica.flutter.ffmpeg
        pluginClass: FlutterFFmpegPlugin
      ios:
        pluginClass: FlutterFFmpegPlugin